name: CI/CD
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - run: |
          curl -RLo jsonschema.zip https://github.com/sourcemeta/jsonschema/releases/download/v11.8.3/jsonschema-11.8.3-linux-x86_64.zip
          echo "4e4fb663549fc6fcde9aa705bd6ce75294b846dec47bf155aaa5af89f0501cff  jsonschema.zip" | sha256sum -c -
          unzip -j jsonschema.zip

      - run: ./jsonschema lint abm/schemas dep/schemas anb/schemas

      - run: ./jsonschema fmt -c abm/schemas dep/schemas anb/schemas
