name: CI/CD
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - run: curl -RLO https://github.com/sourcemeta/jsonschema/releases/download/v11.8.0/jsonschema-11.8.0-linux-x86_64.zip

      - run: unzip -j jsonschema-*.zip

      - run: ./jsonschema lint abm/schemas dep/schemas anb/schemas

      - run: ./jsonschema fmt -c abm/schemas dep/schemas anb/schemas
